baseURL: "https://arkalim.org"
languageCode: en-us
title: Laasya Nellore
theme: PaperMod

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
#     - identifier: blog
#       name: Blog
#       url: /blog
#       weight: 20
    - identifier: projects
      name: Projects
      url: /projects
      weight: 30
    - identifier: experience
      name: Experience
      url: /experience
      weight: 40
    - identifier: search
      name: Search
      url: /search
      weight: 50
    # - identifier: tags
    #   name: Tags
    #   url: /tags
    #   weight: 60
    # - identifier: notes
    #   name: Notes
    #   url: https://notes.arkalim.org
    #   weight: 70

params:
  # theme
  showToc: true
  TocOpen: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideMeta: false

  # for enchanced SEO
  env: production

  # Home Page
  profileMode:
    enabled: true
    title: "Laasya Priya Reddy Nellore"
    subtitle: Hi 👋! I'm Laasya, currently pursuing Master of Science in Data Science from the University of Arizona. As a Data Analyst at the College of Medicine, University of Arizona, I'm deeply involved in cutting-edge research focused on organ donor-recipient compatibility. What makes my work particularly exciting is that we're leveraging the latest advancements in natural language processing (NLP) and Optical Character Recognition (OCR) technology, inspired by recent developments in AI models like ChatGPT.
    imageUrl: "home/laasya.jpg"
    imageWidth: 220
    imageHeight: 220
    buttons:
      - name: Resume
        url: "https://docs.google.com/document/d/1hJ60NRn2o8jvqKAnfRZD4fdUIkg6EDIj/edit#heading=h.gjdgxs"

  # List View
  hideDescriptionInList: false

  # cover image for posts
  cover:
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  socialIcons:
    - name: "email"
      url: "mailto:laasyanellore@arizona.edu"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/laasya-priya-reddy-nellore/"
    - name: "github"
      url: "https://github.com/laasyane11ore"
#     - name: "youtube"
#       url: "https://www.youtube.com/c/AbdurRahmanKalim"
#     - name: "cv"
#       url: "https://drive.google.com/file/d/1U6Gg2RnHSCthtWLbZJBlAEI3V1WGjZty/view"

  # text search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# for search using Fuse.js
outputs:
  home:
    - HTML
    - RSS
    - JSON

# allow HTML in MD
markup:
  goldmark:
    renderer:
      unsafe: true
